"""Single-language desktop text; source data remains unchanged."""
TEXT = {
    "date_help": ("请输入有效的 YYYY-MM-DD 日期，起始日期不能晚于截至日期。上次成功结果已保留，请按快照日期阅读。", "Enter valid YYYY-MM-DD dates; the start cannot be after the end. The last successful result is retained at its snapshot date."),
    "date_order": ("起始日期晚于截至日期。", "Start date is after the end date."),
    "queue_filter": ("仅筛选措施跟进", "Action follow-up filter only"),
    "filter_inactive": ("此页显示完整快照；措施筛选仅适用于措施跟进。", "This tab uses the full snapshot; the action filter applies only to Action follow-up."),
    "workbench": ("质量复核工作台", "Quality review workbench"),
    "open_review": ("打开复核报告", "Open review report"),
    "review_queue": ("措施跟进", "Action follow-up"),
    "review_aging": ("积压分布", "Backlog age"),
    "review_monthly": ("月度变化", "Monthly movements"),
    "batch360": ("批次全景", "Batch overview"),
    "batch_id": ("批次编号", "Batch ID"),
    "select_batch": ("请在措施表选择一行，或从批次列表选择编号。", "Select an action row or a batch ID from the list."),
    "review_hint": ("选中措施后查看批次，联查检验、偏差和全部措施。时间排序不代表质量风险。", "Select an action to trace its batch, measurements, deviations and all actions. Time ordering is not quality-risk ranking."),
    "review_counts": ("显示 {shown} / {total} 条快照记录", "Showing {shown} / {total} snapshot rows"),
    "review_focus": ("逾期或 7 天内到期", "Overdue or due within 7 days"),
    "review_all": ("全部未完成措施", "All outstanding actions"),
    "review_closed_parent": ("偏差已关闭，措施未完成", "Closed parent, outstanding action"),
    "overdue": ("逾期未完成", "Overdue"),
    "due_today": ("今天到期", "Due today"),
    "due_soon": ("1–7 天内到期", "Due in 1–7 days"),
    "later": ("7 天以后到期", "Due later"),
    "outstanding_actions": ("未完成措施", "Outstanding actions"),
    "closed_parent_followup": ("已关闭偏差的未完成措施", "Outstanding actions on closed parents"),
    "review_scope": ("7 天提醒和积压分段为示例。偏差关闭但措施未完成仅提示复核，不证明违规；不评价 CAPA 有效性。最后一期截至分析日期。", "The 7-day horizon and age bands are illustrative. Outstanding actions on closed deviations prompt review, not proof of noncompliance or CAPA effectiveness. The last period ends on the as-of date."),
    "compare": ("③ 对比两个日期", "3. Compare dates"),
    "comparison": ("日期变化对比", "Date comparison"),
    "from_date": ("对比起始日期", "Compare from"),
    "compare_to": ("对比至上方截至日期", "To the as-of date above"),
    "view_comparison": ("查看已有对比", "View comparison"),
    "comparison_dates": ("同一份数据：{start} → {end}", "Same input snapshot: {start} → {end}"),
    "compare_note": ("变化依据事件日期，不代表编辑历史或原因。主窗口显示对比截至日期的结果。新增逾期是两端快照之差，不是期间全部逾期次数。", "Changes use event dates, not edit history or proof of cause. The main view shows the end date. Newly overdue is a difference between endpoints, not all overdue episodes in the interval."),
    "changed_only": ("只看发生变化的记录", "Changed records only"),
    "comparison_count": ("显示 {visible} / {total} 条；没有记录表示本类无符合条件的变化。", "Showing {visible} / {total} rows. An empty view means no matching movements."),
    "comparison_metrics": ("指标变化", "Metrics"),
    "comparison_deviations": ("偏差变化", "Deviations"),
    "comparison_actions": ("逾期变化", "Overdue"),
    "comparison_measurements": ("新增检验", "Measurements"),
    "new_measurement": ("新增检验", "New measurement"),
    "opened_still_open": ("期间开启且仍未关闭", "Opened and still open"),
    "opened_and_closed": ("期间开启并关闭", "Opened and closed in interval"),
    "closed_since_start": ("期初积压已关闭", "Opening backlog closed"),
    "still_open": ("持续未关闭", "Still open"),
    "newly_overdue": ("新进入期末逾期", "New to ending overdue list"),
    "resolved_overdue": ("期初逾期已完成", "Opening overdue completed"),
    "still_overdue": ("持续逾期", "Still overdue"),
    "title": ("BatchScope · 批次质量洞察", "BatchScope"),
    "subtitle": ("药企质量运营分析 · 模拟数据 · 本地处理", "Pharmaceutical quality operations analytics · Synthetic data · Local processing"),
    "generate": ("① 生成演示数据", "1. Generate demo data"),
    "browse": ("选择数据文件夹", "Browse input folder"),
    "as_of": ("截至日期", "As of"),
    "analyse": ("② 运行分析", "2. Analyse"),
    "results": ("结果文件夹", "Results folder"),
    "ready": ("先生成或选择演示数据，然后运行分析。", "Generate or select demo inputs, then run the analysis."),
    "generated": ("已生成 100 个模拟批次，请点击运行分析。", "100 synthetic batches generated. Run the analysis next."),
    "working": ("正在校验输入并分析，请稍候…", "Validating inputs and analysing…"),
    "completed": ("分析完成", "Completed"),
    "failed": ("分析失败", "Failed"),
    "partial": ("未生成完整分析；如有 INPUT_ISSUES.csv，请查看。", "No complete analysis. Inspect INPUT_ISSUES.csv if present."),
    "details": ("查看选中记录", "View record details"),
    "hint": ("双击或右键表格行查看明细；点击列名可排序。", "Double-click or right-click a row for details. Click a heading to sort."),
    "scope": ("仅模拟演示。超范围标记需复核，不能据此放行批次或宣称合规。", "Synthetic demonstration. Range flags require review; no batch-release or compliance decisions."),
    "01_test_ranges": ("检验范围", "Test ranges"),
    "02_deviation_backlog": ("偏差积压", "Deviation backlog"),
    "03_overdue_actions": ("逾期措施", "Overdue actions"),
    "snapshot": ("本次分析截至：{date}", "Snapshot as of: {date}"),
    "status": ("状态", "Status"),
    "search": ("搜索批次、编号或状态", "Search batch, ID or status"),
    "all": ("全部", "All"),
    "showing": ("显示 {visible} / {total} 条组内记录", "Showing {visible} / {total} group records"),
    "full_group": ("整组", "Full group"),
    "source_dates": ("源关闭/完成日期可能晚于分析日期，请以截至日期状态复核。— 表示不可用，不是零。", "Source closure/completion dates can be later than the snapshot; use the as-of status. — means unavailable, not zero."),
    "copy_row": ("复制选中行（含表头）", "Copy selected row with headers"),
    "copy_id": ("复制编号或产品名称", "Copy record ID or product name"),
    "copy_done": ("已复制选中行", "Selected row copied"),
    "copy_id_done": ("已复制编号或产品名称", "ID or product name copied"),
    "select_row": ("请先选择表格中的一行。", "Select a table row first."),
    "check_input": ("检查输入", "Check input"),
    "select_input": ("请先生成或选择模拟数据文件夹。", "Generate or select a synthetic input folder first."),
    "folder_dialog": ("选择包含四个 CSV 和 SOURCE.json 的文件夹", "Choose a folder with four CSV files and SOURCE.json"),
    "running": ("正在运行", "Running"),
    "wait_close": ("请等待分析结束后关闭。", "Wait for the analysis to finish before closing."),
    "light": ("浅色模式", "Light mode"),
    "dark": ("深色模式", "Dark mode"),
    "measured_records": ("检验记录", "Measurements"),
    "judgeable_records": ("可判定", "Judgeable"),
    "missing_records": ("缺失", "Missing"),
    "outside_range_records": ("超范围", "Outside range"),
    "open_deviations": ("未关闭偏差", "Open deviations"),
    "overdue_actions": ("逾期措施", "Overdue actions"),
}


def tr(key, language="zh", **values):
    return TEXT[key][1 if language == "en" else 0].format(**values)
